# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muxXQ27cuiihvjRodqfm4P9K_s4iRntq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")


df.head()

df.info()


df.describe()


df.isnull().sum()

df['Age'].fillna(df['Age'].median(), inplace=True)


df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)


df.drop(columns=['Cabin'], inplace=True)


df.isnull().sum()

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Survived', palette="coolwarm")
plt.title("Survival Count")
plt.xticks([0, 1], ["Not Survived", "Survived"])
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Sex', hue='Survived', palette="coolwarm")
plt.title("Survival Count by Gender")
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(data=df, x='Pclass', hue='Survived', palette="coolwarm")
plt.title("Survival Count by Passenger Class")
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df['Age'], bins=30, kde=True, color='blue')
plt.title("Age Distribution of Passengers")
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt


numeric_df = df.select_dtypes(include=['number'])

plt.figure(figsize=(10, 6))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

df.to_csv("cleaned_titanic.csv", index=False)

from google.colab import files
files.download("cleaned_titanic.csv")